### ISSUE TITLE
Change name displayed when creating job request !

### ISSUE THREAD

**Issue by duynguyenfpt** [duynguyenfpt/CAPSTONE_WS#114]
![image](https://user-images.githubusercontent.com/39914280/126802262-e95a47cf-416c-4dcb-b66d-d7cbaf80b6d2.png)

Please add "is_all" along with "type-id" as you've done!

**Comment by LinhCancer2306** [comment]
Please check this bug in branch https://github.com/duynguyenfpt/CAPSTONE_WS/tree/bugfix/bug-114 @phichphichs

**Comment by duynguyenfpt** [comment]
HI @LinhCancer2306 , @phichphichs 
Anh check, nhưng em có thể thay thế tên bảng cho id không ?  A vừa check lại  - ví dụ như này : Synctable - Students - All .

Tuy nhiên tất cả các request hiện tại là "All" nhưng em đang hiển thị Not All
