### ISSUE TITLE
[Right Screen] Check display of this section

### ISSUE THREAD

**Issue by duynguyenfpt** [duynguyenfpt/CAPSTONE_WS#123]
![image](https://user-images.githubusercontent.com/39914280/126901309-7d37f3f2-eff9-4f5d-904f-dc66fb89c10f.png)

**Comment by LinhCancer2306** [comment]
@phichphichs  this bug was fixed in branch: https://github.com/duynguyenfpt/CAPSTONE_WS/tree/feat/update-detail-job

**Comment by duynguyenfpt** [comment]
Anh test oke
