### ISSUE TITLE
[Database Config][Show list] Don't have [Host] column in Database Config screen

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#48]
![image](https://user-images.githubusercontent.com/53659473/125618446-ec05b7a5-76b0-4403-a877-abfefc01f064.png)

Thiếu cột Host trong bảng database list 
Thiếu cột Host trong bảng database detail

**Comment by LinhCancer2306** [comment]
@vulong22121999 Please add value to `host` field

**Comment by LinhCancer2306** [comment]
@phichphichs  pleae check this bug again in br: https://github.com/duynguyenfpt/CAPSTONE_WS/tree/bugfix/bug-48

**Comment by phichphichs** [comment]
@duynguyenfpt @vulong22121999 
API chưa trả về HOST

**Comment by phichphichs** [comment]
Bug đã được fix. Please merge and close issue @duynguyenfpt 
![image](https://user-images.githubusercontent.com/53659473/126497759-797da94b-225e-4f40-afce-1cae4c5d1927.png)
