### ISSUE TITLE
[Database Config][Create DB] Username and Database Name can input only number

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#49]
![image](https://user-images.githubusercontent.com/53659473/125619441-d9ba9053-89b6-4f33-b138-340357ff90d6.png)

Expected: Input cả chữ và số, nhưng không được input mình số
Actual: Có thể input value toàn số 

Hãy fix lại như expected.

**Comment by duynguyenfpt** [comment]
@phichphichs  ghi rõ nhé, QA nắm rõ chi tiết validate của input. Thực tế là không được bắt đầu bằng số.
Detail anh muốn bám sát theo link này : 
[ấn vào đây](https://www.arangodb.com/docs/stable/data-modeling-naming-conventions-database-names.html#:~:text=Database%20names%20must%20always%20start,Database%20names%20are%20case%2Dsensitive)

**Comment by duynguyenfpt** [comment]
@LinhCancer2306 fix nhé

**Comment by LinhCancer2306** [comment]
@phichphichs  this bug was fixed. Please check again!

**Comment by LinhCancer2306** [comment]
please check this bug again in branch https://github.com/duynguyenfpt/CAPSTONE_WS/tree/bugfix/bug-49

**Comment by phichphichs** [comment]
@duynguyenfpt @LinhCancer2306 
Bug đã được fix theo 2 ý:
- Không được input toàn số: OK
- Không được input ký tự đầu tiên bằng số: OK
Tuy nhiên, cho em confirm thêm
Nếu input ký tự đầu tiên là [ _ ] có được không?
Hiện tại đang input được ký tự đầu tiên là dấu gạch ngang [ _ ]
![image](https://user-images.githubusercontent.com/53659473/126208362-6784a424-0830-45c0-befe-1a8d79f93c06.png)

Nhờ anh Duy confirm

**Comment by phichphichs** [comment]
merge vào anh DUy @duynguyenfpt , cái này anh confirm ok rồi
