### ISSUE TITLE
[Database Config][Show Detail] Display wrong Data Type

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#50]
![image](https://user-images.githubusercontent.com/53659473/125629362-bab7dc7c-ec64-44b7-8422-9e4133a80932.png)
![image](https://user-images.githubusercontent.com/53659473/125629454-0cf6d624-2d5c-4f11-ba24-b8f20fc12f5b.png)

Expected: Oracle (Hình 1)
                  SQL-SERVER (Hình 2)
Actual: Đang hiển thị value dạng key của database type

**Comment by duynguyenfpt** [comment]
@LinhCancer2306 fix nhé chú ý là 'oracal' là sai typo đấy , rất thiếu chuyên nghiệp. Đúng ra là Oracle

**Comment by LinhCancer2306** [comment]
@vulong22121999 please fix `oracal` to `oracle` in be

**Comment by LinhCancer2306** [comment]
@phichphichs  please check this bug again

**Comment by LinhCancer2306** [comment]
please check this bug again in branch https://github.com/duynguyenfpt/CAPSTONE_WS/tree/bugfix/bug-50

**Comment by phichphichs** [comment]
@duynguyenfpt @LinhCancer2306 
Bug đã được fix.
![image](https://user-images.githubusercontent.com/53659473/126205838-f14aeb4e-2283-486b-a5df-351a7450d27b.png)

Nhưng với màn Show List Database
Khi search có 2 vấn đề xảy ra:

>  Database Type: dữ liệu từ value (viết hoa) trở thành key (viết thường)

> Created Date: Từ Invalide Date => Hiển thị Date 

Init Screen
![image](https://user-images.githubusercontent.com/53659473/126206325-6b8a02e7-bfef-4392-adc6-81b491f91154.png)

After search
![image](https://user-images.githubusercontent.com/53659473/126206105-f6cc58ec-0602-4c12-8958-d56f6de61c25.png)

Please check it.

**Comment by LinhCancer2306** [comment]
@phichphichs  Please check again

**Comment by phichphichs** [comment]
@vulong22121999  sửa phần invalid date khi mới vào màn hình
