### ISSUE TITLE
[Database Config][Delete] Missing message when delete failed

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#51]
**Issue:** Không thể xoá Database Config
1. Click delete Database đang liên kết với nhiều bảng khác

**Expected:** 
Có thể delete DB
Display message delete success

**Actual:** 

Show message error 500
![image](https://user-images.githubusercontent.com/53659473/125631843-ef89af02-cfbb-4ad9-bd2c-4feae8c94a58.png)

**Comment by duynguyenfpt** [comment]
Message should be shown or displayed with more detail content 
@LinhCancer2306 check
