### ISSUE TITLE
[Table Config][Delete] Can not delete table 

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#52]
**Issue:** Không thể xoá table
1. Xoá table  record không có liên kết dữ liệu với các bảng khác
2. Click delete

**Tần số:** Lúc xoá được lúc không
**Expected:** 
Delete table và hiển thị message xoá thành công

**Actual:**
Không thể delete table và hiển thị message error 500

**Comment by duynguyenfpt** [comment]
Thống nhất chuyển thành soft delete rồi nhé , @vulong22121999 fix xong thì báo lại

**Comment by duynguyenfpt** [comment]
Chuyển từ bug thành feature vì team vừa thống nhất lại

**Comment by duynguyenfpt** [comment]
@LinhCancer2306 phối hợp hiển thị

**Comment by LinhCancer2306** [comment]
This bug was fixed in BE

**Comment by phichphichs** [comment]
@duynguyenfpt 
Bug đã được fix.
Close this issue
