### ISSUE TITLE
[Table Config][Add Table] Add table has tablename existed in DB

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#53]
**Issue:** Có thể Add table trùng tên trong cùng 1 Database Config
1. Click Add table trong màn hình Database Detail hoặc màn hình Table Config
2. Nhập tên table name đã có trong cùng Database

**Expected:** 
Thêm table thất bại

**Actual:**
Thêm table thành công

**Comment by duynguyenfpt** [comment]
Cái này trong db xoá hết dữ liệu trùng nhau đi @vulong22121999 
Còn phía front-end phải fix validate lại bằng call API phía backend xây dựng

Chốt là @LinhCancer2306  thêm bước check
@vulong22121999  trả api check exist
