### ISSUE TITLE
[Database Config][Check connection] Check connection return error 400

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#54]
**Issue:** Chưa thực hiện được check connection

**Expected:**  Check connection hoạt động

**Actual:** Check connection chưa hoạt động

**Comment by duynguyenfpt** [comment]
@phichphichs vậy đây là thiếu chức năng hả em ?

**Comment by phichphichs** [comment]
@duynguyenfpt Vâng, thiếu chức năng check connection. Anh có thể chuyển thành log future và assign cho dev.

**Comment by duynguyenfpt** [comment]
@vulong22121999 @LinhCancer2306  phối hợp ra api ghép lại nhé
