### ISSUE TITLE
[Change Log][Filter] Filter follow DB wrong

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#55]
*Issue*: Search theo DB ra kết quả sai
Search theo DB and Table ra kết quả đúng
Search theo Db, Table và Change Type ra kết quả đúng

Filter theo ShopeeDB nhưng kết quả vẫn có LazadaDB
![image](https://user-images.githubusercontent.com/53659473/125652904-f273cdf2-b8fd-489f-907b-0ec78d2bb9d0.png)

**Comment by duynguyenfpt** [comment]
@vulong22121999 check lại đang filter theo điều kiện gì
