### ISSUE TITLE
[Change Log][Reload] Not reload dropdown Database, table, change type after click Reload

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#56]
Issue: 
Các dropdown Database, Table, Change Type không được reload lại khi click button Reload.
![image](https://user-images.githubusercontent.com/53659473/125653437-ed826844-f346-4f5c-87d7-673185b9c2f9.png)

**Comment by duynguyenfpt** [comment]
Thiếu feature reload
@vulong22121999  @LinhCancer2306

**Comment by LinhCancer2306** [comment]
please check this bug again in branch https://github.com/duynguyenfpt/CAPSTONE_WS/tree/bugfix/bug-56

**Comment by phichphichs** [comment]
@duynguyenfpt  @LinhCancer2306 

Bug đã được fix.
Các dropdown đã được reload sau khi click Reload button

![image](https://user-images.githubusercontent.com/53659473/126205110-9a1496e6-2aec-4723-b896-271a005fa827.png)

Please close this ticket.
Thank You.

**Comment by duynguyenfpt** [comment]
A vừa merge vào branch main rồi nhé @phichphichs check lại lần nữa nha rồi anh close
