### ISSUE TITLE
[Server Config][Update] Validate Server Domain wrong

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#57]
Issue: Message validate luôn hiển thị
1. Click edit/create server config
=> Message validate phần Server Domain luôn hiển thị

![image](https://user-images.githubusercontent.com/53659473/125658040-bfec8260-4dfc-4586-9768-3cd965e6a01e.png)

**Comment by duynguyenfpt** [comment]
@LinhCancer2306 fix

**Comment by LinhCancer2306** [comment]
@phichphichs please check this bug again in branch https://github.com/duynguyenfpt/CAPSTONE_WS/tree/bugfix/bug-57

**Comment by phichphichs** [comment]
@duynguyenfpt @LinhCancer2306 

Bug đã được fix ở phần Server Domain
Validate theo dạng _**chữ/số+ ".", kết thúc bằng chữ/số**_ : OK

Tuy nhiên phần Server Host:
Chưa hiểu Linh đang validate như nào

Ví dụ nhập:


![image](https://user-images.githubusercontent.com/53659473/126210102-72b06170-f212-44a9-a7d9-e56038ebe438.png)

**Comment by duynguyenfpt** [comment]
Em ơi, dải ip thì nó nằm từ 0-255, không được vượt quá range đấy nên 351 không được

**Comment by phichphichs** [comment]
@duynguyenfpt @LinhCancer2306 
Oki đã hiểu.
Vậy còn Trường hợp Domain là localhost thì cho pass.
Linh fix nốt.

**Comment by duynguyenfpt** [comment]
@LinhCancer2306  if (domain = 'localhost') thì oke em nhé , không check bằng regex nữa

**Comment by phichphichs** [comment]
@duynguyenfpt bug is fixed
