### ISSUE TITLE
[Server Config][Search] Rediect error sreen after click search

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#58]
**Issue:** Không thể search
1. Input giá trị cần search
2. Click button search

**Expected:** Search ra kết quả đúng

**Actual:** Redirect error screen
![image](https://user-images.githubusercontent.com/53659473/125658939-210045e7-a83b-4b61-a0bb-ccd3dfbaea60.png)

**Comment by duynguyenfpt** [comment]
Có thể chỗ này đã áp dụng phân quyền + token
@LinhCancer2306  @vulong22121999  trả lời  giúp anh để xác định bug hay gì
