### ISSUE TITLE
[Request][Edit Request] Change active textbox to inactive textbox in Request Type

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#60]
**Issue:** 

Trong popup Edit Request có trường Request Type đang để text box,
người dùng có thể tuỳ ý nhập các Request Type khác mặc định.
![image](https://user-images.githubusercontent.com/53659473/126027290-b95224b5-1a39-4e12-9bc2-e00628eb0857.png)

**Cách giải quyết:** 
Chuyển textbox => inactive
Người dùng không thể thay đỏi Request Type

**Comment by duynguyenfpt** [comment]
@LinhCancer2306  RequestType không được update

**Comment by LinhCancer2306** [comment]
@phichphichs please check thif bug again https://github.com/duynguyenfpt/CAPSTONE_WS/tree/bugfix/bug-60-63-64

**Comment by phichphichs** [comment]
@duynguyenfpt bug đã được fix, merge and close
