### ISSUE TITLE
[Request][Update] Message success is not same as other screen

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#61]
Issue:

Message update của popup Edit Request không đồng bộ với các màn hình khác.
![image](https://user-images.githubusercontent.com/53659473/126027916-51a8e9fb-ef29-499a-b44a-152e53f53c06.png)

Expected: 
=> Sửa message thành:
Update Request Succeeded

**Comment by duynguyenfpt** [comment]
@LinhCancer2306

**Comment by duynguyenfpt** [comment]
@phichphichs Request is updated successfully chứ nhỉ nhỉ ?

**Comment by LinhCancer2306** [comment]
@phichphichs please check this bug again in branch https://github.com/duynguyenfpt/CAPSTONE_WS/tree/bugfix/bug-61

**Comment by phichphichs** [comment]
@LinhCancer2306 @duynguyenfpt 
Không thể check được vì update request bị lỗi 

![image](https://user-images.githubusercontent.com/53659473/126321517-b80adbf4-3334-41e4-b5cb-ff49e126d2b1.png)

**Comment by duynguyenfpt** [comment]
This one is finished !!
