### ISSUE TITLE
[Request][Update] Update failed because don't find id

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#62]
Issue:
1. Click Edit Request trong record được hiển thị trên list Request
2. Click Update
Không update thành công vì báo lỗi không tìm thấy id
![image](https://user-images.githubusercontent.com/53659473/126028307-623271e8-0c9b-4bd4-9291-0f6af4f7fc78.png)

Expected:
1. Update thành công
2. Sửa message báo lỗi của hệ thống thành message báo lỗi của mình: Thay text: [Updated failed, can't find this record]

**Comment by duynguyenfpt** [comment]
@vulong22121999 @LinhCancer2306
