### ISSUE TITLE
[Request][Update] Dropdown don't display data from DB

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#63]
Issue:
1. Click Edit Request của record
2. Popup Edit Request, dropdown [Approved By] and [Staus] không hiển thị data 
![image](https://user-images.githubusercontent.com/53659473/126028582-efdb7afb-f454-4947-9f2e-774c9392f2bc.png)

Expected:
Hiển thị data của 2 dropdown

**Comment by duynguyenfpt** [comment]
ApprovedBy => Dropdown Search Box.
RequestType => Disable , can not be changed !
Status => 3 statuses, no need to be loaded from database, just hard code is fine !

@LinhCancer2306 @phichphichs h

**Comment by phichphichs** [comment]
@duynguyenfpt @LinhCancer2306 

Sửa thêm với yêu cầu: 

Status -> Reject và approved
![image](https://user-images.githubusercontent.com/53659473/126500430-0475b755-2d9e-4d54-9ea9-0d339df03026.png)
Approved -> drop down search
![image](https://user-images.githubusercontent.com/53659473/126500460-b3c66c67-1cb4-4bf0-b4bc-f2f5a1d39873.png)
