### ISSUE TITLE
[Request][Update] Require dropdown [Approved By] and [Status] when update request

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#64]
Khi update không được để trống [Approved By] and [Status]

=> Làm validate cho 2 dropdown này

**Yêu cầu:**
Không được để trống
Show message dưới dropdown

**Comment by duynguyenfpt** [comment]
@LinhCancer2306

**Comment by phichphichs** [comment]
@duynguyenfpt @LinhCancer2306 
Bug đã được fix. Chờ bug 63 fix ok rồi merge cùng.
