### ISSUE TITLE
[Request][Show list] Display wrong value [Status] column

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#65]
Issue:
Hiển thị sai giá trị của cột Status trong list Request

Ở FE đang set:
<img width="349" alt="getStatus (status) {" src="https://user-images.githubusercontent.com/53659473/126029106-71afa3e7-48ee-4994-8f5b-ea3a259e96d5.png">

Ở BE đang set:
<img width="150" alt="Opending" src="https://user-images.githubusercontent.com/53659473/126029114-172738cc-c782-49d5-8b3d-870a119c0d6d.png">

Expected:
Sửa theo BE

**Comment by duynguyenfpt** [comment]
@LinhCancer2306 li
nên sửa theo BE vì phía FE sẽ ko ảnh hưởng tới nhiều hệ thống

**Comment by LinhCancer2306** [comment]
@phichphichs  please check this bug again in branch https://github.com/duynguyenfpt/CAPSTONE_WS/tree/bugfix/bug-65

**Comment by phichphichs** [comment]
@LinhCancer2306 @duynguyenfpt 
Hiển thị đúng. Bug đã được fix.
Anh Duy merge vào nha
In DB
![image](https://user-images.githubusercontent.com/53659473/126319963-6230ae61-a0e3-4708-9ee1-6281b9426f71.png)
in screen

![image](https://user-images.githubusercontent.com/53659473/126320345-8ef861d8-373c-4c6e-918a-f1ea6191437a.png)

**Comment by duynguyenfpt** [comment]
Oki em, anh merge roi check lai nhe

**Comment by phichphichs** [comment]
@duynguyenfpt  check ok rồi. Anh close bug này
