### ISSUE TITLE
[Request][Create][Synchronized] Items [Id] has wrong type

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#66]
Issue:
Phần id đang để input number
Trên thực tế là input tên cột

![image](https://user-images.githubusercontent.com/53659473/126032552-28e4d449-a92d-437a-b27a-1ab01dd1e617.png)

Expected:
Anh Duy mô tả chi tiết hơn cho phần này vào đây

**Comment by duynguyenfpt** [comment]
Phần này chính là các cột để định dạng unique row cho một bảng, ví dụ bảng student sẽ có student_id, bảng product sẽ có product_id, chính xác hơn đây sẽ nhập [candidate key](https://www.guru99.com/dbms-keys.html) của bảng đó.
Expect giao diện bản chất vẫn là **dropdown search box** , kết hợp với hiển thị sẽ là như này:

Ở mục add & remove dynamically : https://ant.design/components/tag/

**Comment by duynguyenfpt** [comment]
A từng dặn @LinhCancer2306 là đấy không ghi id cho tránh nhầm lẫn : em ghi hẳn là candidate key cũng được, chắc chắn đầu vào là danh sách các cột.

**Comment by duynguyenfpt** [comment]
Thêm 1 text box là Partion by nữa @LinhCancer2306

**Comment by LinhCancer2306** [comment]
@phichphichs  https://github.com/duynguyenfpt/CAPSTONE_WS/tree/bugfix/bug-66
