### ISSUE TITLE
[Account][Create Account] FE spelling mistake 

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#71]
Sai chính tả:
Creat Job => Create job
Creat Request => Create Request
![image](https://user-images.githubusercontent.com/53659473/126066023-d271f450-cd27-4111-af1a-876aa6bc240b.png)

**Comment by duynguyenfpt** [comment]
Lần sau close thì chuyển tag thành done nhé @LinhCancer2306
