### ISSUE TITLE
[Account][Create Account] Validate wrong [Phone] input

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#72]
Issue:
Nhập 10 số => báo sai
Nhập 11 số => báo sai

![image](https://user-images.githubusercontent.com/53659473/126066089-0217a671-3c3f-45db-b855-51de83080bd7.png)

Yêu cầu:
Người dùng có thể input từ 9 -> 11 số

**Comment by LinhCancer2306** [comment]
@phichphichs Please close this bug!!!

**Comment by duynguyenfpt** [comment]
@LinhCancer2306 a close r nha
