### ISSUE TITLE
[Account][Create Account] Dropdown Copy Right don't mapping DB

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#73]
Issue:
Data trong dropdown Copy Right không đúng với DB
in Webservice:
![image](https://user-images.githubusercontent.com/53659473/126067031-b219df0d-8ec7-4687-bfb6-f29ed9086958.png)
in DB
![image](https://user-images.githubusercontent.com/53659473/126067052-f9641109-3925-4b95-b709-ab9d786de850.png)

Yêu cầu:
Mapping với accounts.username trong DB

**Comment by LinhCancer2306** [comment]
please check this bug again in branch https://github.com/duynguyenfpt/CAPSTONE_WS/tree/bugfix/bug-73

**Comment by phichphichs** [comment]
@duynguyenfpt @LinhCancer2306 
Bug đã được fix.
Nhờ anh Duy merge vào nhánh.
Thank you.
