### ISSUE TITLE
[Request][Note] Yêu cầu thêm về giao diện View Note

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#75]
![image](https://user-images.githubusercontent.com/53659473/126201455-839dbf89-2003-4b62-8d17-c441955b180b.png)

**> Tên popup:** 

- Log Note => View Note

**> Giao diện:** 

- Thay username bằng tên người dùng login
-  Để giao diện sao cho phân biệt được 2 người đang chat (Để note message khác màu hoặc cho lùi phải, lùi trái message note)

**Comment by duynguyenfpt** [comment]
Long xử lý cái phần này cho gọn

**Comment by duynguyenfpt** [comment]
@vulong22121999
