### ISSUE TITLE
[Request][Assgin Job] Add button assign job

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#76]
Yêu cầu thêm chức năng:

**Assign Job**

> **Định dạng:** Dropdown list

> **onClick:** Show data username của bảng account

> **Yêu cầu:** Drop down có thể search

> **Ví dụ minh hoạ:**
![image](https://user-images.githubusercontent.com/53659473/126202341-64e69631-03a7-4b11-b8e1-64c8b59e2d38.png)

**Comment by duynguyenfpt** [comment]
This feature is no need
