### ISSUE TITLE
Pagination does not display properly

### ISSUE THREAD

**Issue by duynguyenfpt** [duynguyenfpt/CAPSTONE_WS#84]
![image](https://user-images.githubusercontent.com/39914280/126280872-9f905882-8109-4ea0-8abf-e024a6bec63d.png)

There is one result but pagination still show multiple pages

**Comment by LinhCancer2306** [comment]
@vulong22121999  please fix this bug

**Comment by LinhCancer2306** [comment]
@phichphichs please check this bug in branch https://github.com/duynguyenfpt/CAPSTONE_WS/tree/bugfix/bug-84
