### ISSUE TITLE
[Request][View Detail Request] Yêu cầu thêm chức năng view detail

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#94]
Thêm chức năng view detail request: 

![image](https://user-images.githubusercontent.com/53659473/126365819-f72128e9-8488-4535-8913-8b9919c06191.png)

Anh Duy nói rõ hơn về phần này

**Comment by duynguyenfpt** [comment]
Khi em tạo request, sẽ có 3 option, mỗi option sẽ được lưu vào 1 bảng. Load detail thì load tương ứng với request nhé e
