### ISSUE TITLE
[Job][View List][View Detail][Create][Reset Job][Assign Job] Update FE, BE follow new DB of JOB

### ISSUE THREAD

**Issue by phichphichs** [duynguyenfpt/CAPSTONE_WS#97]
Job vừa thêm các trường mới trong DB nên hiện tại không show đủ dữ liệu lên màn hình
**Xem lại tất cả các chức năng màn này**

**Lưu ý các chức năng:** 

1. Assign Job tách ra thành 1 chức năng riêng, không nằm trong phần [Excecuted By] của Create Job nữa
2. Show log job ở phần detail chưa có API (issue 77)
3. Add button Reset (Issue 78)
4. Update wrong (issue 95)

![image](https://user-images.githubusercontent.com/53659473/126370381-a7f56a6b-e0f2-4b3d-8539-ee1f7716dca5.png)

**Comment by duynguyenfpt** [comment]
Em check lại ở trên Master nhé @phichphichs

**Comment by duynguyenfpt** [comment]
Finished !
